[env:henry-s3-board]
extends = esp32s3_base
board = esp32-s3-devkitc-1-n16r8v      ; Crucial: Tells PlatformIO to configure 16MB Flash / 8MB PSRAM
board_level = extra                    ; Prevents the core build matrix from throwing warnings

build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW                         ; Informs Meshtastic this is a custom, non-production board
  -I variants/esp32s3/henry_s3_board   ; Points the compiler to your local pin definition header
