[env:henry-s3-board]
extends = esp32s3_base
board = esp32-s3-devkitc-1     ; Crucial: Tells PlatformIO to configure 16MB Flash / 8MB PSRAM
board_level = extra                    ; Prevents the core build matrix from throwing warnings

# Explicitly configure Octal Flash (16MB) and Octal PSRAM (8MB)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
# Add these missing parameters to force-override the boot mode mismatch
board_build.f_flash = 80mhz
board_build.f_cpu = 240000000L

build_flags =
  ${esp32s3_base.build_flags}
  -DBOARD_HAS_PSRAM
  -D HAS_SCREEN=1
  -D PRIVATE_HW                         ; Informs Meshtastic this is a custom, non-production board
  -I variants/esp32s3/henry_s3_board   ; Points the compiler to your local pin definition header
  -D LORA_RXEN=4                        ; Binds hardware RF switch RX line to Pin 4 at firmware compilation
  -D LORA_TXEN=9                        ; Binds hardware RF switch TX line to Pin 9 at firmware compilation
  -D HAS_NEOPIXEL                       ; Tells Meshtastic to activate the WS2812 RGB driver
  -D NEOPIXEL_DATA=48                    ; Maps the WS2812 Data Line to GPIO 48
  -D NEOPIXEL_COUNT=1                   ; Tells the driver there is 1 single built-in RGB LED
  -D NEOPIXEL_TYPE=NEO_GRB+NEO_KHZ800
